#!/usr/bin/env python3
"""
Toffoli Optimizer Optimization Sweep Script (Revised for specific repo structure)

This script sweeps through different optimization methods and parameters
for a quantum circuit generated by the save_circuit script, comparing
their performance in terms of depth reduction, gate count, and fidelity.

Usage:
    python optimization_sweep_revised.py --input <toffoli_network_file> --output <results_dir>
                                        [--topology linear|grid|falcon] [--visualize]
"""

import os
import sys
import time
import json
import argparse
from datetime import datetime
import matplotlib.pyplot as plt
import numpy as np

# First, let's check what modules are available in your repository
available_modules = {}

# Try to import the compiler
try:
    from toffoli_optimizer.core.compiler import ToffoliCompiler, ToffoliType
    available_modules["compiler"] = True
    print("Successfully imported ToffoliCompiler")
except ImportError as e:
    available_modules["compiler"] = False
    print(f"Could not import ToffoliCompiler: {e}")

# Try to import the RLToffoliOptimizer
try:
    from toffoli_optimizer.core.optimizer import RLToffoliOptimizer
    available_modules["rl_optimizer"] = True
    print("Successfully imported RLToffoliOptimizer")
except ImportError as e:
    available_modules["rl_optimizer"] = False
    print(f"Could not import RLToffoliOptimizer: {e}")

# Try to import the ZXOptimizer
try:
    from toffoli_optimizer.core.zx_optimizer import ZXOptimizer
    available_modules["zx_optimizer"] = True
    print("Successfully imported ZXOptimizer")
except ImportError as e:
    available_modules["zx_optimizer"] = False
    print(f"Could not import ZXOptimizer: {e}")

# Try to import utility functions
try:
    from toffoli_optimizer.utils.io_utils import define_loaded_toffoli_network, save_circuit_to_qasm
    available_modules["io_utils"] = True
    print("Successfully imported I/O utilities")
except ImportError as e:
    available_modules["io_utils"] = False
    print(f"Could not import I/O utilities: {e}")

try:
    from toffoli_optimizer.utils.circuit_utils import get_default_coupling_map
    available_modules["circuit_utils"] = True
    print("Successfully imported circuit utilities")
except ImportError as e:
    available_modules["circuit_utils"] = False
    print(f"Could not import circuit utilities: {e}")

try:
    from toffoli_optimizer.utils.visualization import save_circuit_image
    available_modules["visualization"] = True
    print("Successfully imported visualization utilities")
except ImportError as e:
    available_modules["visualization"] = False
    print(f"Could not import visualization utilities: {e}")

# Check if we have the necessary components to proceed
essential_modules = ["compiler", "io_utils", "circuit_utils"]
missing_modules = [m for m in essential_modules if not available_modules.get(m, False)]

if missing_modules:
    print(f"Error: The following essential modules are missing: {', '.join(missing_modules)}")
    print("Please ensure the repository is properly installed.")
    sys.exit(1)

def parse_args():
    """Parse command line arguments"""
    parser = argparse.ArgumentParser(description='Toffoli Circuit Optimization Sweep')
    
    parser.add_argument('--input', type=str, required=True,
                       help='Input file containing the Toffoli network (without extension)')
    
    parser.add_argument('--output', type=str, default='optimization_sweep_results',
                       help='Output directory for optimization results')
    
    parser.add_argument('--topology', type=str, default='linear',
                       choices=['linear', 'grid', 'falcon'], 
                       help='Target topology')
    
    parser.add_argument('--num-trials', type=int, default=3,
                       help='Number of optimization trials (default: 3)')
    
    parser.add_argument('--visualize', action='store_true',
                       help='Generate visualizations of results')
    
    parser.add_argument('--debug', action='store_true',
                       help='Enable debug mode')
    
    # Advanced parameters for the sweep
    parser.add_argument('--target-fidelities', type=str, default='0.85,0.90,0.95,0.99',
                       help='Comma-separated list of target fidelities to sweep')
    
    return parser.parse_args()

def create_results_table(all_results, output_file):
    """Create a formatted results table as a text file"""
    with open(output_file, 'w') as f:
        f.write("Toffoli Circuit Optimization Sweep Results\n")
        f.write("=" * 80 + "\n\n")
        
        # Write a summary table
        f.write(f"{'Method':<20} {'Fidelity':<10} {'Original Depth':<15} ")
        f.write(f"{'Optimized Depth':<15} {'Depth Reduction':<15} ")
        f.write(f"{'Gate Count':<12} {'CX Count':<10} {'Runtime (s)':<12}\n")
        f.write("-" * 120 + "\n")
        
        for method, results_by_fidelity in sorted(all_results.items()):
            for fidelity, result in sorted(results_by_fidelity.items()):
                # Extract key metrics
                original_depth = result.get("original_depth", 0)
                optimized_depth = result.get("optimized_depth", 0)
                depth_reduction = result.get("depth_reduction", 0)
                gate_count = result.get("gate_count", 0)
                cx_count = result.get("cx_count", 0)
                runtime = result.get("runtime", 0)
                
                # Format and write the row
                f.write(f"{method:<20} {float(fidelity):<10.3f} {original_depth:<15} ")
                f.write(f"{optimized_depth:<15} {depth_reduction:<15.2f} ")
                f.write(f"{gate_count:<12} {cx_count:<10} {runtime:<12.2f}\n")
        
        # Add a summary of the best results
        f.write("\n\nBest Results:\n")
        f.write("-" * 60 + "\n")
        
        # Find the best depth reduction
        best_depth_reduction = 0
        best_method = ""
        best_fidelity = 0
        
        for method, results_by_fidelity in all_results.items():
            for fidelity, result in results_by_fidelity.items():
                depth_reduction = result.get("depth_reduction", 0)
                if depth_reduction > best_depth_reduction:
                    best_depth_reduction = depth_reduction
                    best_method = method
                    best_fidelity = fidelity
        
        f.write(f"Best depth reduction: {best_depth_reduction:.2f}% achieved by:\n")
        f.write(f"  Method: {best_method}\n")
        f.write(f"  Target fidelity: {best_fidelity}\n")
        
        # Find the best tradeoff (depth reduction / runtime)
        best_tradeoff = 0
        best_tradeoff_method = ""
        best_tradeoff_fidelity = 0
        
        for method, results_by_fidelity in all_results.items():
            for fidelity, result in results_by_fidelity.items():
                depth_reduction = result.get("depth_reduction", 0)
                runtime = result.get("runtime", 1)  # Avoid division by zero
                tradeoff = depth_reduction / runtime if runtime > 0 else 0
                
                if tradeoff > best_tradeoff:
                    best_tradeoff = tradeoff
                    best_tradeoff_method = method
                    best_tradeoff_fidelity = fidelity
        
        f.write(f"\nBest efficiency (depth reduction / runtime): {best_tradeoff:.2f} achieved by:\n")
        f.write(f"  Method: {best_tradeoff_method}\n")
        f.write(f"  Target fidelity: {best_tradeoff_fidelity}\n")
        
        # End with timestamp
        f.write(f"\n\nResults generated at: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")

def plot_comparison_chart(all_results, output_file):
    """Create a comparison chart of different optimization methods"""
    # Extract data for plotting
    methods = []
    original_depths = []
    optimized_depths = []
    depth_reductions = []
    
    # Prepare data
    for method, results_by_fidelity in sorted(all_results.items()):
        for fidelity, result in sorted(results_by_fidelity.items()):
            method_name = f"{method} (f={fidelity})"
            methods.append(method_name)
            
            original_depths.append(result.get("original_depth", 0))
            optimized_depths.append(result.get("optimized_depth", 0))
            depth_reductions.append(result.get("depth_reduction", 0))
    
    # Create the figure
    plt.figure(figsize=(14, 10))
    
    # Plot the depths
    plt.subplot(2, 1, 1)
    x = np.arange(len(methods))
    width = 0.35
    
    plt.bar(x - width/2, original_depths, width, label='Original Depth')
    plt.bar(x + width/2, optimized_depths, width, label='Optimized Depth')
    
    plt.ylabel('Circuit Depth')
    plt.title('Circuit Depth Comparison Across Optimization Methods')
    plt.xticks(x, methods, rotation=45, ha='right')
    plt.legend()
    plt.grid(axis='y', alpha=0.3)
    
    # Plot depth reduction
    plt.subplot(2, 1, 2)
    
    plt.bar(x, depth_reductions, width, label='Depth Reduction (%)')
    
    plt.ylabel('Depth Reduction (%)')
    plt.title('Optimization Performance')
    plt.xticks(x, methods, rotation=45, ha='right')
    plt.legend()
    plt.grid(axis='y', alpha=0.3)
    
    plt.tight_layout()
    plt.savefig(output_file)
    plt.close()

def optimize_with_rl(circuit, coupling_map, target_fidelity, num_trials=3, debug=False):
    """Optimize circuit using RL optimizer if available"""
    if not available_modules.get("rl_optimizer", False):
        print("RL optimizer not available, skipping")
        return None
    
    try:
        # Create the RL optimizer
        optimizer = RLToffoliOptimizer(
            target_fidelity=target_fidelity,
            max_steps=30,  # Reasonable default
            debug_mode=debug
        )
        
        best_depth = float('inf')
        best_result = None
        
        for trial in range(num_trials):
            print(f"  RL Optimization trial {trial+1}/{num_trials}...")
            start_time = time.time()
            
            # Run optimization
            optimized_circuit = optimizer.optimize_circuit(circuit.copy(), coupling_map=coupling_map)
            
            # Check if we got a better result
            if optimized_circuit.depth() < best_depth:
                best_depth = optimized_circuit.depth()
                best_result = {
                    "circuit": optimized_circuit,
                    "runtime": time.time() - start_time,
                    "original_depth": circuit.depth(),
                    "optimized_depth": optimized_circuit.depth(),
                    "depth_reduction": ((circuit.depth() - optimized_circuit.depth()) / circuit.depth() * 100) 
                                      if circuit.depth() > 0 else 0,
                    "gate_count": len(optimized_circuit.data),
                    "cx_count": sum(1 for g in optimized_circuit.data if g.operation.name == 'cx')
                }
        
        return best_result
    
    except Exception as e:
        print(f"Error running RL optimization: {e}")
        import traceback
        traceback.print_exc()
        return None

def optimize_with_zx(circuit, coupling_map, target_fidelity, debug=False):
    """Optimize circuit using ZX optimizer if available"""
    if not available_modules.get("zx_optimizer", False):
        print("ZX optimizer not available, skipping")
        return None
    
    try:
        # Create the ZX optimizer
        aggressive_mode = (target_fidelity < 0.9)
        zx_optimizer = ZXOptimizer(
            aggressive_mode=aggressive_mode,
            target_fidelity=target_fidelity,
            debug_mode=debug
        )
        
        # Run optimization
        start_time = time.time()
        optimized_circuit = zx_optimizer.optimize_circuit(circuit.copy(), coupling_map=coupling_map)
        
        # Return the result
        return {
            "circuit": optimized_circuit,
            "runtime": time.time() - start_time,
            "original_depth": circuit.depth(),
            "optimized_depth": optimized_circuit.depth(),
            "depth_reduction": ((circuit.depth() - optimized_circuit.depth()) / circuit.depth() * 100) 
                              if circuit.depth() > 0 else 0,
            "gate_count": len(optimized_circuit.data),
            "cx_count": sum(1 for g in optimized_circuit.data if g.operation.name == 'cx')
        }
    
    except Exception as e:
        print(f"Error running ZX optimization: {e}")
        import traceback
        traceback.print_exc()
        return None

def optimize_with_transpiler(circuit, coupling_map, optimization_level=3):
    """Optimize circuit using Qiskit's transpiler"""
    try:
        from qiskit import transpile
        
        start_time = time.time()
        optimized_circuit = transpile(
            circuit.copy(),
            coupling_map=coupling_map,
            optimization_level=optimization_level
        )
        
        return {
            "circuit": optimized_circuit,
            "runtime": time.time() - start_time,
            "original_depth": circuit.depth(),
            "optimized_depth": optimized_circuit.depth(),
            "depth_reduction": ((circuit.depth() - optimized_circuit.depth()) / circuit.depth() * 100) 
                              if circuit.depth() > 0 else 0,
            "gate_count": len(optimized_circuit.data),
            "cx_count": sum(1 for g in optimized_circuit.data if g.operation.name == 'cx'),
            "optimization_level": optimization_level
        }
    
    except Exception as e:
        print(f"Error running transpiler optimization: {e}")
        import traceback
        traceback.print_exc()
        return None

def run_optimization_sweep(toffoli_gates, output_qubits, input_qubits, num_qubits, 
                          topology, num_trials, target_fidelities, debug, output_dir):
    """
    Run a sweep of various optimization methods on the input circuit.
    
    Args:
        toffoli_gates: List of Toffoli gates
        output_qubits: List of output qubit indices
        input_qubits: List of input qubit indices
        num_qubits: Number of qubits in the circuit
        topology: Target topology ('linear', 'grid', 'falcon')
        num_trials: Number of optimization trials
        target_fidelities: List of target fidelities to try
        debug: Whether to enable debug output
        output_dir: Directory for output files
        
    Returns:
        dict: Dictionary with all optimization results
    """
    print(f"Running optimization sweep for {len(toffoli_gates)} Toffoli gates on {num_qubits} qubits")
    print(f"Target topology: {topology}")
    print(f"Number of trials: {num_trials}")
    print(f"Target fidelities: {target_fidelities}")
    
    # Create compiler
    compiler = ToffoliCompiler(debug_mode=debug)
    
    # Get coupling map
    coupling_map = get_default_coupling_map(topology, num_qubits)
    
    # Create a logical circuit
    logical_circuit, _ = compiler.create_toffoli_network(
        toffoli_gates,
        num_qubits,
        use_ancilla=True
    )
    
    if logical_circuit is None:
        print("Error: Failed to create logical circuit")
        return {}
    
    print(f"Created logical circuit with depth {logical_circuit.depth()}")
    
    # Results dictionary
    all_results = {}
    
    # Save the original circuit details
    original_dir = os.path.join(output_dir, "original")
    os.makedirs(original_dir, exist_ok=True)
    
    save_circuit_to_qasm(
        logical_circuit,
        os.path.join(original_dir, "original_circuit.qasm")
    )
    
    if available_modules.get("visualization", False):
        try:
            save_circuit_image(
                logical_circuit,
                "original_circuit",
                output_dir=original_dir,
                use_text_mode=True
            )
        except Exception as e:
            print(f"Warning: Could not save original circuit image: {e}")
    
    # 1. Run transpiler optimization with different levels
    all_results["Transpile_L1"] = {}
    all_results["Transpile_L2"] = {}
    all_results["Transpile_L3"] = {}
    
    print("\n=== Running Qiskit Transpiler Optimization ===")
    
    for level in [1, 2, 3]:
        method_name = f"Transpile_L{level}"
        print(f"\nRunning transpiler with optimization level {level}...")
        
        for fidelity in target_fidelities:
            # Transpiler doesn't use fidelity directly, but we track it for comparison
            result = optimize_with_transpiler(logical_circuit, coupling_map, level)
            if result:
                result["target_fidelity"] = fidelity
                all_results[method_name][fidelity] = result
                
                print(f"  Level {level}, Fidelity {fidelity}:")
                print(f"    Original depth: {result['original_depth']}")
                print(f"    Optimized depth: {result['optimized_depth']}")
                print(f"    Depth reduction: {result['depth_reduction']:.2f}%")
                print(f"    Runtime: {result['runtime']:.2f} seconds")
                
                # Save the optimized circuit
                method_dir = os.path.join(output_dir, f"{method_name}_f{fidelity}")
                os.makedirs(method_dir, exist_ok=True)
                
                save_circuit_to_qasm(
                    result["circuit"],
                    os.path.join(method_dir, "optimized_circuit.qasm")
                )
                
                if available_modules.get("visualization", False):
                    try:
                        save_circuit_image(
                            result["circuit"],
                            "optimized_circuit",
                            output_dir=method_dir,
                            use_text_mode=True
                        )
                    except Exception as e:
                        print(f"Warning: Could not save circuit image: {e}")
    
    # 2. Run RL optimization if available
    if available_modules.get("rl_optimizer", False):
        print("\n=== Running RL Optimization ===")
        all_results["RL_Optimizer"] = {}
        
        for fidelity in target_fidelities:
            print(f"\nRunning RL optimization with target fidelity {fidelity}...")
            
            result = optimize_with_rl(logical_circuit, coupling_map, fidelity, num_trials, debug)
            if result:
                result["target_fidelity"] = fidelity
                all_results["RL_Optimizer"][fidelity] = result
                
                print(f"  Target fidelity {fidelity}:")
                print(f"    Original depth: {result['original_depth']}")
                print(f"    Optimized depth: {result['optimized_depth']}")
                print(f"    Depth reduction: {result['depth_reduction']:.2f}%")
                print(f"    Runtime: {result['runtime']:.2f} seconds")
                
                # Save the optimized circuit
                method_dir = os.path.join(output_dir, f"RL_Optimizer_f{fidelity}")
                os.makedirs(method_dir, exist_ok=True)
                
                save_circuit_to_qasm(
                    result["circuit"],
                    os.path.join(method_dir, "optimized_circuit.qasm")
                )
                
                if available_modules.get("visualization", False):
                    try:
                        save_circuit_image(
                            result["circuit"],
                            "optimized_circuit",
                            output_dir=method_dir,
                            use_text_mode=True
                        )
                    except Exception as e:
                        print(f"Warning: Could not save circuit image: {e}")
    
    # 3. Run ZX optimization if available
    if available_modules.get("zx_optimizer", False):
        print("\n=== Running ZX Optimization ===")
        all_results["ZX_Optimizer"] = {}
        
        for fidelity in target_fidelities:
            print(f"\nRunning ZX optimization with target fidelity {fidelity}...")
            
            result = optimize_with_zx(logical_circuit, coupling_map, fidelity, debug)
            if result:
                result["target_fidelity"] = fidelity
                all_results["ZX_Optimizer"][fidelity] = result
                
                print(f"  Target fidelity {fidelity}:")
                print(f"    Original depth: {result['original_depth']}")
                print(f"    Optimized depth: {result['optimized_depth']}")
                print(f"    Depth reduction: {result['depth_reduction']:.2f}%")
                print(f"    Runtime: {result['runtime']:.2f} seconds")
                
                # Save the optimized circuit
                method_dir = os.path.join(output_dir, f"ZX_Optimizer_f{fidelity}")
                os.makedirs(method_dir, exist_ok=True)
                
                save_circuit_to_qasm(
                    result["circuit"],
                    os.path.join(method_dir, "optimized_circuit.qasm")
                )
                
                if available_modules.get("visualization", False):
                    try:
                        save_circuit_image(
                            result["circuit"],
                            "optimized_circuit",
                            output_dir=method_dir,
                            use_text_mode=True
                        )
                    except Exception as e:
                        print(f"Warning: Could not save circuit image: {e}")
    
    return all_results

def save_serializable_results(results, output_file):
    """Save results to a JSON file, handling non-serializable objects"""
    serializable_results = {}
    
    for method, results_by_fidelity in results.items():
        serializable_results[method] = {}
        
        for fidelity, result in results_by_fidelity.items():
            # Create a serializable copy
            serializable_result = {}
            
            for key, value in result.items():
                # Skip non-serializable objects like circuits
                if key != "circuit":
                    serializable_result[key] = value
            
            serializable_results[method][fidelity] = serializable_result
    
    with open(output_file, 'w') as f:
        json.dump(serializable_results, f, indent=2)

def main():
    """Main function"""
    # Parse command line arguments
    args = parse_args()
    
    # Create output directory
    os.makedirs(args.output, exist_ok=True)
    
    # Load the input Toffoli network
    print(f"Loading Toffoli network from {args.input}")
    result = define_loaded_toffoli_network(args.input, debug=args.debug)
    
    if result is None:
        print(f"Error: Failed to load Toffoli network from {args.input}")
        return 1
    
    toffoli_gates, output_qubits, input_qubits = result
    
    # Determine number of qubits if not specified
    num_qubits = max([max(controls + [target]) for controls, target in toffoli_gates]) + 1
    num_qubits = max(8, num_qubits)  # Ensure at least 8 qubits
    
    print(f"Loaded Toffoli network with {len(toffoli_gates)} gates on {num_qubits} qubits")
    print(f"Input qubits: {input_qubits}")
    print(f"Output qubits: {output_qubits}")
    
    # Parse target fidelities
    target_fidelities = [float(f.strip()) for f in args.target_fidelities.split(',')]
    
    # Run the optimization sweep
    all_results = run_optimization_sweep(
        toffoli_gates,
        output_qubits,
        input_qubits,
        num_qubits,
        args.topology,
        args.num_trials,
        target_fidelities,
        args.debug,
        args.output
    )
    
    # Save results
    results_file = os.path.join(args.output, "results.json")
    save_serializable_results(all_results, results_file)
    print(f"Results saved to {results_file}")
    
    # Create results table
    table_file = os.path.join(args.output, "results_table.txt")
    create_results_table(all_results, table_file)
    print(f"Results table saved to {table_file}")
    
    # Generate visualizations if requested
    if args.visualize:
        chart_file = os.path.join(args.output, "optimization_comparison.png")
        plot_comparison_chart(all_results, chart_file)
        print(f"Comparison chart saved to {chart_file}")
    
    print("\nOptimization sweep completed successfully!")
    return 0

if __name__ == "__main__":
    sys.exit(main())
