#!/usr/bin/env python3
"""
Toffoli Optimizer Adapter and Optimization Sweep Script

This script adapts the existing ConsolidatedToffoliDepthOptimizer to the interface
expected by the optimization sweep script, and then runs the sweep on a circuit
generated by the save_circuit module.

Usage:
    python optimization_sweep_adapter.py --input <toffoli_network_file> --output <results_dir>
                                        [--topology linear|grid|falcon] [--visualize]
"""

import os
import sys
import time
import json
import argparse
from datetime import datetime
import matplotlib.pyplot as plt
import numpy as np
import importlib.util
import traceback

# Define paths to import local modules if installed via setup.py
sys.path.append(os.path.abspath('.'))
sys.path.append(os.path.abspath('..'))

class ToffoliDepthOptimizerAdapter:
    """
    Adapter class that wraps ConsolidatedToffoliDepthOptimizer to match the expected interface.
    """
    
    def __init__(self, target_fidelity=0.95, max_passes=2, debug_mode=False, output_dir=None):
        """Initialize the adapter with the given parameters."""
        self.target_fidelity = target_fidelity
        self.max_passes = max_passes
        self.debug_mode = debug_mode
        self.output_dir = output_dir or "optimization_results"
        
        # Import ConsolidatedToffoliDepthOptimizer dynamically
        try:
            # Check if optimizer.py exists and load it
            optimizer_path = os.path.join(os.path.dirname(__file__), "toffoli_optimizer", "core", "optimizer.py")
            if not os.path.exists(optimizer_path):
                optimizer_path = os.path.join(os.path.dirname(__file__), "..", "toffoli_optimizer", "core", "optimizer.py")
            
            spec = importlib.util.spec_from_file_location("optimizer_module", optimizer_path)
            optimizer_module = importlib.util.module_from_spec(spec)
            spec.loader.exec_module(optimizer_module)
            
            # Get the optimizer class - try different possible names
            if hasattr(optimizer_module, "ConsolidatedToffoliDepthOptimizer"):
                self.optimizer_class = optimizer_module.ConsolidatedToffoliDepthOptimizer
                print("Using ConsolidatedToffoliDepthOptimizer")
            elif hasattr(optimizer_module, "ToffoliDepthOptimizer"):
                self.optimizer_class = optimizer_module.ToffoliDepthOptimizer
                print("Using ToffoliDepthOptimizer")
            elif hasattr(optimizer_module, "EnhancedToffoliDepthOptimizer"):
                self.optimizer_class = optimizer_module.EnhancedToffoliDepthOptimizer
                print("Using EnhancedToffoliDepthOptimizer")
            else:
                # Fallback - create a dummy optimizer
                print("No suitable optimizer found in optimizer.py")
                self.optimizer_class = type('DummyOptimizer', (), {'__init__': lambda self, **kwargs: None})
        
        except Exception as e:
            print(f"Error importing optimizer: {e}")
            traceback.print_exc()
            # Create a dummy optimizer class as fallback
            self.optimizer_class = type('DummyOptimizer', (), {'__init__': lambda self, **kwargs: None})
        
        # Create the optimizer instance
        self.optimizer = self.optimizer_class(
            target_fidelity=target_fidelity,
            max_passes=max_passes,
            debug_mode=debug_mode,
            output_dir=self.output_dir
        )
        
        # Import compiler dynamically
        try:
            # Check if compiler.py exists and load it
            compiler_path = os.path.join(os.path.dirname(__file__), "toffoli_optimizer", "core", "compiler.py")
            if not os.path.exists(compiler_path):
                compiler_path = os.path.join(os.path.dirname(__file__), "..", "toffoli_optimizer", "core", "compiler.py")
            
            spec = importlib.util.spec_from_file_location("compiler_module", compiler_path)
            compiler_module = importlib.util.module_from_spec(spec)
            spec.loader.exec_module(compiler_module)
            
            # Get the compiler class
            if hasattr(compiler_module, "ToffoliCompiler"):
                self.compiler_class = compiler_module.ToffoliCompiler
                print("Using ToffoliCompiler")
                self.compiler = self.compiler_class(debug_mode=debug_mode)
                self.optimizer.compiler = self.compiler
            else:
                print("ToffoliCompiler not found in compiler.py")
                self.compiler_class = None
                self.compiler = None
        
        except Exception as e:
            print(f"Error importing compiler: {e}")
            traceback.print_exc()
            self.compiler_class = None
            self.compiler = None
    
    def optimize_toffoli_network(self, toffoli_gates, output_qubits, input_qubits, num_qubits, 
                              topology=None, coupling_map=None, basis_gates=None, target_fidelity=None,
                              original_circuit=None, logical_circuit=None):
        """
        Adapt and call the underlying optimizer with the given parameters.
        """
        try:
            # Call the actual optimizer
            results = self.optimizer.optimize_toffoli_network(
                toffoli_gates=toffoli_gates,
                output_qubits=output_qubits,
                input_qubits=input_qubits,
                num_qubits=num_qubits,
                topology=topology,
                coupling_map=coupling_map,
                basis_gates=basis_gates,
                target_fidelity=target_fidelity or self.target_fidelity,
                original_circuit=original_circuit,
                logical_circuit=logical_circuit
            )
            
            # Ensure results has all expected fields
            if "naive_physical" not in results and "original" in results:
                results["naive_physical"] = results["original"]
            
            if "naive_physical" not in results:
                results["naive_physical"] = {
                    "depth": 0,
                    "gate_count": 0,
                    "cx_count": 0,
                    "t_gates": 0,
                    "circuit": None
                }
            
            if "logical" not in results:
                results["logical"] = {
                    "depth": 0,
                    "gate_count": 0,
                    "cx_count": 0,
                    "t_gates": 0,
                    "circuit": None
                }
            
            if "optimized" not in results and "final" in results:
                results["optimized"] = results["final"]
                
            if "optimized" not in results:
                results["optimized"] = {
                    "depth": 0,
                    "gate_count": 0,
                    "cx_count": 0,
                    "t_gates": 0,
                    "circuit": None
                }
            
            if "mapped" not in results and "physical" in results:
                results["mapped"] = results["physical"]
                
            if "mapped" not in results:
                results["mapped"] = {
                    "depth": 0,
                    "gate_count": 0,
                    "cx_count": 0,
                    "t_gates": 0,
                    "circuit": None
                }
            
            return results
            
        except Exception as e:
            print(f"Error in optimize_toffoli_network adapter: {e}")
            traceback.print_exc()
            
            # Return a minimal error result
            return {
                "error": str(e),
                "logical": {"depth": 0, "circuit": None},
                "naive_physical": {"depth": 0, "circuit": None},
                "optimized": {"depth": 0, "circuit": None},
                "mapped": {"depth": 0, "circuit": None},
                "depth_reduction": 0,
                "optimization_time": 0
            }

# Define and load utility functions similar to the original script
def load_io_utils():
    """Dynamically load IO utilities."""
    try:
        # Check if io_utils.py exists and load it
        io_utils_path = os.path.join(os.path.dirname(__file__), "toffoli_optimizer", "utils", "io_utils.py")
        if not os.path.exists(io_utils_path):
            io_utils_path = os.path.join(os.path.dirname(__file__), "..", "toffoli_optimizer", "utils", "io_utils.py")
        
        spec = importlib.util.spec_from_file_location("io_utils_module", io_utils_path)
        io_utils_module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(io_utils_module)
        
        # Get the necessary functions
        if hasattr(io_utils_module, "define_loaded_toffoli_network"):
            define_loaded_toffoli_network = io_utils_module.define_loaded_toffoli_network
            print("Found define_loaded_toffoli_network function")
        else:
            define_loaded_toffoli_network = lambda filename, debug=False: ([], [], [])
            print("define_loaded_toffoli_network function not found")
        
        if hasattr(io_utils_module, "save_circuit_to_qasm"):
            save_circuit_to_qasm = io_utils_module.save_circuit_to_qasm
            print("Found save_circuit_to_qasm function")
        else:
            save_circuit_to_qasm = lambda circuit, filename: None
            print("save_circuit_to_qasm function not found")
            
        return define_loaded_toffoli_network, save_circuit_to_qasm
        
    except Exception as e:
        print(f"Error loading IO utilities: {e}")
        traceback.print_exc()
        
        # Return dummy functions
        return (lambda filename, debug=False: ([], [], [])), (lambda circuit, filename: None)

def load_circuit_utils():
    """Dynamically load circuit utilities."""
    try:
        # Check if circuit_utils.py exists and load it
        circuit_utils_path = os.path.join(os.path.dirname(__file__), "toffoli_optimizer", "utils", "circuit_utils.py")
        if not os.path.exists(circuit_utils_path):
            circuit_utils_path = os.path.join(os.path.dirname(__file__), "..", "toffoli_optimizer", "utils", "circuit_utils.py")
        
        spec = importlib.util.spec_from_file_location("circuit_utils_module", circuit_utils_path)
        circuit_utils_module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(circuit_utils_module)
        
        # Get the necessary functions
        if hasattr(circuit_utils_module, "get_default_coupling_map"):
            get_default_coupling_map = circuit_utils_module.get_default_coupling_map
            print("Found get_default_coupling_map function")
        else:
            get_default_coupling_map = lambda topology, num_qubits: []
            print("get_default_coupling_map function not found")
            
        return get_default_coupling_map
        
    except Exception as e:
        print(f"Error loading circuit utilities: {e}")
        traceback.print_exc()
        
        # Return dummy function
        return lambda topology, num_qubits: []

def load_visualization_utils():
    """Dynamically load visualization utilities."""
    try:
        # Check if visualization.py exists and load it
        vis_path = os.path.join(os.path.dirname(__file__), "toffoli_optimizer", "utils", "visualization.py")
        if not os.path.exists(vis_path):
            vis_path = os.path.join(os.path.dirname(__file__), "..", "toffoli_optimizer", "utils", "visualization.py")
        
        spec = importlib.util.spec_from_file_location("visualization_module", vis_path)
        visualization_module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(visualization_module)
        
        # Get the necessary functions
        if hasattr(visualization_module, "save_circuit_image"):
            save_circuit_image = visualization_module.save_circuit_image
            print("Found save_circuit_image function")
        else:
            save_circuit_image = lambda circuit, filename, output_dir="circuit_images", use_text_mode=True: None
            print("save_circuit_image function not found")
            
        return save_circuit_image
        
    except Exception as e:
        print(f"Error loading visualization utilities: {e}")
        traceback.print_exc()
        
        # Return dummy function
        return lambda circuit, filename, output_dir="circuit_images", use_text_mode=True: None

def parse_args():
    """Parse command line arguments"""
    parser = argparse.ArgumentParser(description='Toffoli Circuit Optimization Sweep')
    
    parser.add_argument('--input', type=str, required=True,
                       help='Input file containing the Toffoli network (without extension)')
    
    parser.add_argument('--output', type=str, default='optimization_sweep_results',
                       help='Output directory for optimization results')
    
    parser.add_argument('--topology', type=str, default='linear',
                       choices=['linear', 'grid', 'falcon'], 
                       help='Target topology')
    
    parser.add_argument('--num-trials', type=int, default=3,
                       help='Number of optimization trials (default: 3)')
    
    parser.add_argument('--visualize', action='store_true',
                       help='Generate visualizations of results')
    
    parser.add_argument('--debug', action='store_true',
                       help='Enable debug mode')
    
    # Advanced parameters for the sweep
    parser.add_argument('--target-fidelities', type=str, default='0.85,0.90,0.95,0.99',
                       help='Comma-separated list of target fidelities to sweep')
    
    return parser.parse_args()

def create_results_table(all_results, output_file):
    """Create a formatted results table as a text file"""
    with open(output_file, 'w') as f:
        f.write("Toffoli Circuit Optimization Sweep Results\n")
        f.write("=" * 80 + "\n\n")
        
        # Write a summary table
        f.write(f"{'Method':<20} {'Fidelity':<10} {'Original Depth':<15} ")
        f.write(f"{'Optimized Depth':<15} {'Depth Reduction':<15} ")
        f.write(f"{'Gate Count':<12} {'CX Count':<10} {'Runtime (s)':<12}\n")
        f.write("-" * 120 + "\n")
        
        for method, results_by_fidelity in sorted(all_results.items()):
            for fidelity, result in sorted(results_by_fidelity.items()):
                # Extract key metrics
                original_depth = result.get("original_depth", 0)
                optimized_depth = result.get("optimized_depth", 0)
                depth_reduction = result.get("depth_reduction", 0)
                gate_count = result.get("gate_count", 0)
                cx_count = result.get("cx_count", 0)
                runtime = result.get("runtime", 0)
                
                # Format and write the row
                f.write(f"{method:<20} {float(fidelity):<10.3f} {original_depth:<15} ")
                f.write(f"{optimized_depth:<15} {depth_reduction:<15.2f} ")
                f.write(f"{gate_count:<12} {cx_count:<10} {runtime:<12.2f}\n")
        
        # Add a summary of the best results
        f.write("\n\nBest Results:\n")
        f.write("-" * 60 + "\n")
        
        # Find the best depth reduction
        best_depth_reduction = 0
        best_method = ""
        best_fidelity = 0
        
        for method, results_by_fidelity in all_results.items():
            for fidelity, result in results_by_fidelity.items():
                depth_reduction = result.get("depth_reduction", 0)
                if depth_reduction > best_depth_reduction:
                    best_depth_reduction = depth_reduction
                    best_method = method
                    best_fidelity = fidelity
        
        f.write(f"Best depth reduction: {best_depth_reduction:.2f}% achieved by:\n")
        f.write(f"  Method: {best_method}\n")
        f.write(f"  Target fidelity: {best_fidelity}\n")
        
        # Find the best tradeoff (depth reduction / runtime)
        best_tradeoff = 0
        best_tradeoff_method = ""
        best_tradeoff_fidelity = 0
        
        for method, results_by_fidelity in all_results.items():
            for fidelity, result in results_by_fidelity.items():
                depth_reduction = result.get("depth_reduction", 0)
                runtime = result.get("runtime", 1)  # Avoid division by zero
                tradeoff = depth_reduction / runtime if runtime > 0 else 0
                
                if tradeoff > best_tradeoff:
                    best_tradeoff = tradeoff
                    best_tradeoff_method = method
                    best_tradeoff_fidelity = fidelity
        
        f.write(f"\nBest efficiency (depth reduction / runtime): {best_tradeoff:.2f} achieved by:\n")
        f.write(f"  Method: {best_tradeoff_method}\n")
        f.write(f"  Target fidelity: {best_tradeoff_fidelity}\n")
        
        # End with timestamp
        f.write(f"\n\nResults generated at: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")

def plot_comparison_chart(all_results, output_file):
    """Create a comparison chart of different optimization methods"""
    # Extract data for plotting
    methods = []
    original_depths = []
    optimized_depths = []
    depth_reductions = []
    
    # Prepare data
    for method, results_by_fidelity in sorted(all_results.items()):
        for fidelity, result in sorted(results_by_fidelity.items()):
            method_name = f"{method} (f={fidelity})"
            methods.append(method_name)
            
            original_depths.append(result.get("original_depth", 0))
            optimized_depths.append(result.get("optimized_depth", 0))
            depth_reductions.append(result.get("depth_reduction", 0))
    
    # Create the figure
    plt.figure(figsize=(14, 10))
    
    # Plot the depths
    plt.subplot(2, 1, 1)
    x = np.arange(len(methods))
    width = 0.35
    
    plt.bar(x - width/2, original_depths, width, label='Original Depth')
    plt.bar(x + width/2, optimized_depths, width, label='Optimized Depth')
    
    plt.ylabel('Circuit Depth')
    plt.title('Circuit Depth Comparison Across Optimization Methods')
    plt.xticks(x, methods, rotation=45, ha='right')
    plt.legend()
    plt.grid(axis='y', alpha=0.3)
    
    # Plot depth reduction
    plt.subplot(2, 1, 2)
    
    plt.bar(x, depth_reductions, width, label='Depth Reduction (%)')
    
    plt.ylabel('Depth Reduction (%)')
    plt.title('Optimization Performance')
    plt.xticks(x, methods, rotation=45, ha='right')
    plt.legend()
    plt.grid(axis='y', alpha=0.3)
    
    plt.tight_layout()
    plt.savefig(output_file)
    plt.close()

def create_dummy_optimizer(target_fidelity=0.95, max_passes=2, debug_mode=False):
    """Create a dummy optimizer for testing when modules aren't available."""
    class DummyOptimizer:
        def __init__(self, **kwargs):
            self.target_fidelity = target_fidelity
            self.max_passes = max_passes
            self.debug_mode = debug_mode
            
        def optimize_circuit(self, circuit, coupling_map=None):
            """Dummy optimize circuit method - returns original circuit."""
            print("Using dummy optimizer (no optimization)")
            return circuit
    
    return DummyOptimizer()

def optimize_with_zx(circuit, coupling_map, target_fidelity, debug=False):
    """Optimize circuit using ZX optimizer if available"""
    # Try to import dynamically
    try:
        # Check if the ZX optimizer exists
        zx_optimizer_path = os.path.join(os.path.dirname(__file__), "toffoli_optimizer", "core", "zx_optimizer.py")
        if not os.path.exists(zx_optimizer_path):
            zx_optimizer_path = os.path.join(os.path.dirname(__file__), "..", "toffoli_optimizer", "core", "zx_optimizer.py")
        
        spec = importlib.util.spec_from_file_location("zx_optimizer_module", zx_optimizer_path)
        zx_optimizer_module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(zx_optimizer_module)
        
        # Get the ZX optimizer class
        if hasattr(zx_optimizer_module, "ZXOptimizer"):
            ZXOptimizer = zx_optimizer_module.ZXOptimizer
            print("Using ZXOptimizer")
            
            # Create the ZX optimizer
            aggressive_mode = (target_fidelity < 0.9)
            zx_optimizer = ZXOptimizer(
                aggressive_mode=aggressive_mode,
                target_fidelity=target_fidelity,
                debug_mode=debug
            )
            
            # Run optimization
            start_time = time.time()
            optimized_circuit = zx_optimizer.optimize_circuit(circuit.copy(), coupling_map=coupling_map)
            
            # Return the result
            return {
                "circuit": optimized_circuit,
                "runtime": time.time() - start_time,
                "original_depth": circuit.depth(),
                "optimized_depth": optimized_circuit.depth(),
                "depth_reduction": ((circuit.depth() - optimized_circuit.depth()) / circuit.depth() * 100) 
                                  if circuit.depth() > 0 else 0,
                "gate_count": len(optimized_circuit.data),
                "cx_count": sum(1 for g in optimized_circuit.data if g.operation.name == 'cx')
            }
            
        else:
            print("ZXOptimizer class not found")
            return None
            
    except Exception as e:
        print(f"Error running ZX optimization: {e}")
        traceback.print_exc()
        return None

def optimize_with_transpiler(circuit, coupling_map, optimization_level=3):
    """Optimize circuit using Qiskit's transpiler"""
    try:
        from qiskit import transpile
        
        start_time = time.time()
        optimized_circuit = transpile(
            circuit.copy(),
            coupling_map=coupling_map,
            optimization_level=optimization_level
        )
        
        return {
            "circuit": optimized_circuit,
            "runtime": time.time() - start_time,
            "original_depth": circuit.depth(),
            "optimized_depth": optimized_circuit.depth(),
            "depth_reduction": ((circuit.depth() - optimized_circuit.depth()) / circuit.depth() * 100) 
                              if circuit.depth() > 0 else 0,
            "gate_count": len(optimized_circuit.data),
            "cx_count": sum(1 for g in optimized_circuit.data if g.operation.name == 'cx'),
            "optimization_level": optimization_level
        }
    
    except Exception as e:
        print(f"Error running transpiler optimization: {e}")
        traceback.print_exc()
        return None

def optimize_with_rl(circuit, coupling_map, target_fidelity, num_trials=3, debug=False):
    """Optimize circuit using RL optimizer if available"""
    # Try to import dynamically
    try:
        # Check if the RL optimizer exists
        rl_optimizer_path = os.path.join(os.path.dirname(__file__), "toffoli_optimizer", "core", "rl_optimizer.py")
        if not os.path.exists(rl_optimizer_path):
            rl_optimizer_path = os.path.join(os.path.dirname(__file__), "..", "toffoli_optimizer", "core", "rl_optimizer.py")
        
        spec = importlib.util.spec_from_file_location("rl_optimizer_module", rl_optimizer_path)
        rl_optimizer_module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(rl_optimizer_module)
        
        # Get the RL optimizer class
        if hasattr(rl_optimizer_module, "RLOptimizationWrapper"):
            RLOptimizer = rl_optimizer_module.RLOptimizationWrapper
            print("Using RLOptimizationWrapper")
        elif hasattr(rl_optimizer_module, "RLToffoliOptimizer"):
            RLOptimizer = rl_optimizer_module.RLToffoliOptimizer
            print("Using RLToffoliOptimizer")
        else:
            print("RL optimizer not found")
            return None
        
        # Create the RL optimizer
        optimizer = RLOptimizer(
            target_fidelity=target_fidelity,
            max_steps=30,  # Reasonable default
            debug_mode=debug
        )
        
        best_depth = float('inf')
        best_result = None
        
        for trial in range(num_trials):
            print(f"  RL Optimization trial {trial+1}/{num_trials}...")
            start_time = time.time()
            
            # Run optimization
            optimized_circuit = optimizer.optimize_circuit(circuit.copy(), coupling_map=coupling_map)
            
            # Check if we got a better result
            if optimized_circuit.depth() < best_depth:
                best_depth = optimized_circuit.depth()
                best_result = {
                    "circuit": optimized_circuit,
                    "runtime": time.time() - start_time,
                    "original_depth": circuit.depth(),
                    "optimized_depth": optimized_circuit.depth(),
                    "depth_reduction": ((circuit.depth() - optimized_circuit.depth()) / circuit.depth() * 100) 
                                      if circuit.depth() > 0 else 0,
                    "gate_count": len(optimized_circuit.data),
                    "cx_count": sum(1 for g in optimized_circuit.data if g.operation.name == 'cx')
                }
        
        return best_result
    
    except Exception as e:
        print(f"Error running RL optimization: {e}")
        traceback.print_exc()
        return None

def run_optimization_sweep(toffoli_gates, output_qubits, input_qubits, num_qubits, 
                          topology, num_trials, target_fidelities, debug, output_dir):
    """
    Run a sweep of various optimization methods on the input circuit.
    
    Args:
        toffoli_gates: List of Toffoli gates
        output_qubits: List of output qubit indices
        input_qubits: List of input qubit indices
        num_qubits: Number of qubits in the circuit
        topology: Target topology ('linear', 'grid', 'falcon')
        num_trials: Number of optimization trials
        target_fidelities: List of target fidelities to try
        debug: Whether to enable debug output
        output_dir: Directory for output files
        
    Returns:
        dict: Dictionary with all optimization results
    """
    print(f"Running optimization sweep for {len(toffoli_gates)} Toffoli gates on {num_qubits} qubits")
    print(f"Target topology: {topology}")
    print(f"Number of trials: {num_trials}")
    print(f"Target fidelities: {target_fidelities}")
    
    # Create adapter for ToffoliDepthOptimizer
    compiler = ToffoliDepthOptimizerAdapter(debug_mode=debug)
    
    # Load utility functions
    define_loaded_toffoli_network, save_circuit_to_qasm = load_io_utils()
    get_default_coupling_map = load_circuit_utils()
    save_circuit_image = load_visualization_utils()
    
    # Get coupling map
    coupling_map = get_default_coupling_map(topology, num_qubits)
    
    # Create a logical circuit
    logical_circuit, _ = compiler.compiler.create_toffoli_network(
        toffoli_gates,
        num_qubits,
        use_ancilla=True
    ) if compiler.compiler else None
    
    if logical_circuit is None:
        print("Error: Failed to create logical circuit")
        print("Trying to create a basic circuit...")
        
        # Try to create a basic circuit with Qiskit
        try:
            from qiskit import QuantumCircuit
            logical_circuit = QuantumCircuit(num_qubits)
            
            # Add Toffoli gates to the circuit
            for controls, target in toffoli_gates:
                if len(controls) == 2:
                    logical_circuit.ccx(controls[0], controls[1], target)
                elif len(controls) == 1:
                    logical_circuit.cx(controls[0], target)
                elif len(controls) == 0:
                    logical_circuit.x(target)
                else:
                    logical_circuit.mcx(controls, target)
        except Exception as e:
            print(f"Error creating basic circuit: {e}")
            return {}
    
    print(f"Created logical circuit with depth {logical_circuit.depth()}")
    
    # Results dictionary
    all_results = {}
    
    # Save the original circuit details
    original_dir = os.path.join(output_dir, "original")
    os.makedirs(original_dir, exist_ok=True)
    
    save_circuit_to_qasm(
        logical_circuit,
        os.path.join(original_dir, "original_circuit.qasm")
    )
    
    try:
        save_circuit_image(
            logical_circuit,
            "original_circuit",
            output_dir=original_dir,
            use_text_mode=True
        )
    except Exception as e:
        print(f"Warning: Could not save original circuit image: {e}")
    
    # 1. Run transpiler optimization with different levels
    all_results["Transpile_L1"] = {}
    all_results["Transpile_L2"] = {}
    all_results["Transpile_L3"] = {}
    
    print("\n=== Running Qiskit Transpiler Optimization ===")
    
    for level in [1, 2, 3]:
        method_name = f"Transpile_L{level}"
        print(f"\nRunning transpiler with optimization level {level}...")
        
        for fidelity in target_fidelities:
            # Transpiler doesn't use fidelity directly, but we track it for comparison
            result = optimize_with_transpiler(logical_circuit, coupling_map, level)
            if result:
                result["target_fidelity"] = fidelity
                all_results[method_name][fidelity] = result
                
                print(f"  Level {level}, Fidelity {fidelity}:")
                print(f"    Original depth: {result['original_depth']}")
                print(f"    Optimized depth: {result['optimized_depth']}")
                print(f"    Depth reduction: {result['depth_reduction']:.2f}%")
                print(f"    Runtime: {result['runtime']:.2f} seconds")
                
                # Save the optimized circuit
                method_dir = os.path.join(output_dir, f"{method_name}_f{fidelity}")
                os.makedirs(method_dir, exist_ok=True)
                
                save_circuit_to_qasm(
                    result["circuit"],
                    os.path.join(method_dir, "optimized_circuit.qasm")
                )
                
                try:
                    save_circuit_image(
                        result["circuit"],
                        "optimized_circuit",
                        output_dir=method_dir,
                        use_text_mode=True
                    )
                except Exception as e:
                    print(f"Warning: Could not save circuit image: {e}")
    
    # 2. Run our ToffoliDepthOptimizer
    print("\n=== Running ToffoliDepthOptimizer ===")
    all_results["ToffoliDepthOptimizer"] = {}
    
    for fidelity in target_fidelities:
        print(f"\nRunning ToffoliDepthOptimizer with target fidelity {fidelity}...")
        
        # Create a new adapter for each fidelity
        optimizer = ToffoliDepthOptimizerAdapter(
            target_fidelity=fidelity,
            max_passes=2,
            debug_mode=debug
        )
        
        start_time = time.time()
        optimization_results = optimizer.optimize_toffoli_network(
            toffoli_gates,
            output_qubits,
            input_qubits,
            num_qubits,
            topology=topology,
            coupling_map=coupling_map
        )
        runtime = time.time() - start_time
        
        if "error" not in optimization_results:
            # Extract key metrics
            logical_depth = optimization_results["logical"]["depth"]
            optimized_depth = optimization_results["optimized"]["depth"]
            mapped_depth = optimization_results["mapped"]["depth"]
            
            # Calculate depth reduction
            depth_reduction = ((logical_depth - optimized_depth) / logical_depth * 100) if logical_depth > 0 else 0
            
            result = {
                "circuit": optimization_results["mapped"]["circuit"],
                "runtime": runtime,
                "target_fidelity": fidelity,
                "original_depth": logical_depth,
                "optimized_depth": mapped_depth,
                "depth_reduction": depth_reduction,
                "gate_count": optimization_results["mapped"].get("gate_count", 0),
                "cx_count": optimization_results["mapped"].get("cx_count", 0)
            }
            
            all_results["ToffoliDepthOptimizer"][fidelity] = result
            
            print(f"  Target fidelity {fidelity}:")
            print(f"    Original depth: {logical_depth}")
            print(f"    Optimized depth: {mapped_depth}")
            print(f"    Depth reduction: {depth_reduction:.2f}%")
            print(f"    Runtime: {runtime:.2f} seconds")
            
            # Save the optimized circuit
            method_dir = os.path.join(output_dir, f"ToffoliDepthOptimizer_f{fidelity}")
            os.makedirs(method_dir, exist_ok=True)
            
            save_circuit_to_qasm(
                result["circuit"],
                os.path.join(method_dir, "optimized_circuit.qasm")
            )
            
            try:
                save_circuit_image(
                    result["circuit"],
                    "optimized_circuit",
                    output_dir=method_dir,
                    use_text_mode=True
                )
            except Exception as e:
                print(f"Warning: Could not save circuit image: {e}")
        else:
            print(f"  Error: {optimization_results['error']}")
    
    # 3. Run RL optimization if available
    print("\n=== Running RL Optimization ===")
    all_results["RL_Optimizer"] = {}
    
    for fidelity in target_fidelities:
        print(f"\nRunning RL optimization with target fidelity {fidelity}...")
        
        result = optimize_with_rl(logical_circuit, coupling_map, fidelity, num_trials, debug)
        if result:
            result["target_fidelity"] = fidelity
            all_results["RL_Optimizer"][fidelity] = result
            
            print(f"  Target fidelity {fidelity}:")
            print(f"    Original depth: {result['original_depth']}")
            print(f"    Optimized depth: {result['optimized_depth']}")
            print(f"    Depth reduction: {result['depth_reduction']:.2f}%")
            print(f"    Runtime: {result['runtime']:.2f} seconds")
            
            # Save the optimized circuit
            method_dir = os.path.join(output_dir, f"RL_Optimizer_f{fidelity}")
            os.makedirs(method_dir, exist_ok=True)
            
            save_circuit_to_qasm(
                result["circuit"],
                os.path.join(method_dir, "optimized_circuit.qasm")
            )
            
            try:
                save_circuit_image(
                    result["circuit"],
                    "optimized_circuit",
                    output_dir=method_dir,
                    use_text_mode=True
                )
            except Exception as e:
                print(f"Warning: Could not save circuit image: {e}")
        else:
            print("  RL optimization not available or failed")
    
    # 4. Run ZX optimization if available
    print("\n=== Running ZX Optimization ===")
    all_results["ZX_Optimizer"] = {}
    
    for fidelity in target_fidelities:
        print(f"\nRunning ZX optimization with target fidelity {fidelity}...")
        
        result = optimize_with_zx(logical_circuit, coupling_map, fidelity, debug)
        if result:
            result["target_fidelity"] = fidelity
            all_results["ZX_Optimizer"][fidelity] = result
            
            print(f"  Target fidelity {fidelity}:")
            print(f"    Original depth: {result['original_depth']}")
            print(f"    Optimized depth: {result['optimized_depth']}")
            print(f"    Depth reduction: {result['depth_reduction']:.2f}%")
            print(f"    Runtime: {result['runtime']:.2f} seconds")
            
            # Save the optimized circuit
            method_dir = os.path.join(output_dir, f"ZX_Optimizer_f{fidelity}")
            os.makedirs(method_dir, exist_ok=True)
            
            save_circuit_to_qasm(
                result["circuit"],
                os.path.join(method_dir, "optimized_circuit.qasm")
            )
            
            try:
                save_circuit_image(
                    result["circuit"],
                    "optimized_circuit",
                    output_dir=method_dir,
                    use_text_mode=True
                )
            except Exception as e:
                print(f"Warning: Could not save circuit image: {e}")
        else:
            print("  ZX optimization not available or failed")
    
    return all_results

def save_serializable_results(results, output_file):
    """Save results to a JSON file, handling non-serializable objects"""
    serializable_results = {}
    
    for method, results_by_fidelity in results.items():
        serializable_results[method] = {}
        
        for fidelity, result in results_by_fidelity.items():
            # Create a serializable copy
            serializable_result = {}
            
            for key, value in result.items():
                # Skip circuit objects and other non-serializable things
                if key != "circuit":
                    serializable_result[key] = value
            
            serializable_results[method][fidelity] = serializable_result
    
    with open(output_file, 'w') as f:
        json.dump(serializable_results, f, indent=2)

def main():
    """Main function"""
    # Parse command line arguments
    args = parse_args()
    
    # Create output directory
    os.makedirs(args.output, exist_ok=True)
    
    # Load the utility functions
    define_loaded_toffoli_network, _ = load_io_utils()
    
    # Load the input Toffoli network
    print(f"Loading Toffoli network from {args.input}")
    result = define_loaded_toffoli_network(args.input, debug=args.debug)
    
    if result is None:
        print(f"Error: Failed to load Toffoli network from {args.input}")
        print("Creating a dummy Toffoli network for testing")
        
        # Create a dummy network
        toffoli_gates = [
            ([0, 1], 2),  # Controls: 0,1; Target: 2
            ([0, 1], 3),  # Controls: 0,1; Target: 3
            ([0, 2], 4),  # Controls: 0,2; Target: 4
            ([1, 2], 5),  # Controls: 1,2; Target: 5
            ([2, 3], 6),  # Controls: 2,3; Target: 6
            ([4, 5], 7),  # Controls: 4,5; Target: 7
        ]
        output_qubits = [3, 6, 7]  # Sum bits and carry
        input_qubits = [0, 1, 2]   # Input bits
    else:
        toffoli_gates, output_qubits, input_qubits = result
    
    # Determine number of qubits if not specified
    num_qubits = max([max(controls + [target]) for controls, target in toffoli_gates]) + 1
    num_qubits = max(8, num_qubits)  # Ensure at least 8 qubits
    
    print(f"Loaded Toffoli network with {len(toffoli_gates)} gates on {num_qubits} qubits")
    print(f"Input qubits: {input_qubits}")
    print(f"Output qubits: {output_qubits}")
    
    # Parse target fidelities
    target_fidelities = [float(f.strip()) for f in args.target_fidelities.split(',')]
    
    # Run the optimization sweep
    all_results = run_optimization_sweep(
        toffoli_gates,
        output_qubits,
        input_qubits,
        num_qubits,
        args.topology,
        args.num_trials,
        target_fidelities,
        args.debug,
        args.output
    )
    
    # Save results
    results_file = os.path.join(args.output, "results.json")
    save_serializable_results(all_results, results_file)
    print(f"Results saved to {results_file}")
    
    # Create results table
    table_file = os.path.join(args.output, "results_table.txt")
    create_results_table(all_results, table_file)
    print(f"Results table saved to {table_file}")
    
    # Generate visualizations if requested
    if args.visualize:
        chart_file = os.path.join(args.output, "optimization_comparison.png")
        plot_comparison_chart(all_results, chart_file)
        print(f"Comparison chart saved to {chart_file}")
    
    print("\nOptimization sweep completed successfully!")
    return 0

if __name__ == "__main__":
    sys.exit(main())
